// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateIndex(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateIndex'](arg1, arg2, arg3);
}

export function CreateIndexProgress() {
  return window['go']['main']['App']['CreateIndexProgress']();
}

export function GenerateOverpassQuery(arg1, arg2) {
  return window['go']['main']['App']['GenerateOverpassQuery'](arg1, arg2);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function GetIndexProgress(arg1) {
  return window['go']['main']['App']['GetIndexProgress'](arg1);
}

export function GetOverpassQueryTemplates() {
  return window['go']['main']['App']['GetOverpassQueryTemplates']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListIndexedFiles() {
  return window['go']['main']['App']['ListIndexedFiles']();
}

export function LoadGeospatialFile(arg1) {
  return window['go']['main']['App']['LoadGeospatialFile'](arg1);
}

export function QueryOverpassAPI(arg1) {
  return window['go']['main']['App']['QueryOverpassAPI'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileAsBase64(arg1) {
  return window['go']['main']['App']['ReadFileAsBase64'](arg1);
}

export function SaveEditedOSMData(arg1, arg2) {
  return window['go']['main']['App']['SaveEditedOSMData'](arg1, arg2);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
