// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateIndex(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function CreateIndexProgress():Promise<number>;

export function GenerateOverpassQuery(arg1:string,arg2:Array<number>):Promise<string>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetHomeDirectory():Promise<string>;

export function GetIndexProgress(arg1:number):Promise<main.IndexProgress>;

export function GetOverpassQueryTemplates():Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<Record<string, any>>>;

export function ListIndexedFiles():Promise<Array<main.GeoFileIndex>>;

export function LoadGeospatialFile(arg1:string):Promise<Record<string, any>>;

export function QueryOverpassAPI(arg1:string):Promise<main.OverpassResponse>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileAsBase64(arg1:string):Promise<string>;

export function SaveEditedOSMData(arg1:Record<string, any>,arg2:string):Promise<void>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function SelectDirectory():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
